[features]
seeds = false
[programs.devnet]
checkout_transactions = "4DMFEdzUx65CZRLiuF3dpfRfAvdvmNftQLRuAKq8n3nW"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/axiom/Desktop/Workspace/Axiom/BLOCKCHAIN/Learning/SeCbhUgwfifKUVc3Ut5Z7hRCRMsPyFr1Z4hyargXYYv.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
